// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xngepzgptfnaxejvqodb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ2VwemdwdGZuYXhlanZxb2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Njk3MzksImV4cCI6MjA3MjU0NTczOX0.5t67urPQoJeMgyjNt0tiOWsq7hmipkXGRQboDMiaVtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});